apiVersion: v1
kind: LimitRange
metadata:
  name: foc-default-limits
spec:
  limits:
    - type: Container
      defaultRequest:
        {{- toYaml .Values.defaultContainer.request | nindent 8 }}
      default:
        {{- toYaml .Values.defaultContainer.limit | nindent 8 }}
