apiVersion: v1
kind: Service
metadata:
  name: {{ include "foc-service.name" . }}
  labels:
    {{- include "foc-service.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "foc-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http
